const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const {createServer}=require('node:http');
(async()=>{const root=path.resolve(__dirname,'..');const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');const file=path.resolve(root,'.'+(url.pathname==='/'?'/index.html':decodeURIComponent(url.pathname)));if(!file.startsWith(root+path.sep))return res.writeHead(403).end();try{const body=await fs.readFile(file);res.writeHead(200,{'Content-Type':({'.js':'application/javascript','.html':'text/html','.css':'text/css','.png':'image/png'})[path.extname(file)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let b;
try{b=await chromium.launch({channel:'chrome',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(`http://127.0.0.1:${server.address().port}`);await p.waitForFunction(()=>window.game?.state==='MENU');await p.locator('#btn-start').click();await p.waitForFunction(()=>window.game.state==='PLAYING');
const result=await p.evaluate(async()=>{const T=await import('/libs/three.module.js');const {Zombie}=await import('/src/enemies.js');const g=window.game;g.state='PAUSED';g.player.setInputEnabled(false);g.waveManager.clear();g.player.reset(new T.Vector3(0,0,3));g.player.model.position.copy(g.player.position);g.player.mixer.update(.2);g.weapons.updateHeldPose(g.player.model);
 const cross=g.player.position.clone();for(let i=0;i<100;i++)g.arena.moveCharacter(cross,0,-.1,g.player.radius);
 const gun=g.weapons.weaponMeshes.blaster;const dimensions=new T.Box3().setFromObject(gun).getSize(new T.Vector3());const dir=new T.Vector3(0,0,1).applyQuaternion(gun.getWorldQuaternion(new T.Quaternion()));const expected=new T.Vector3(0,0,1).applyQuaternion(g.player.model.getWorldQuaternion(new T.Quaternion()));
 const muzzle=g.weapons.getMuzzlePosition();g.weapons.shoot(muzzle,g.player.position.clone().add(new T.Vector3(0,1,-10)),false,true);const shotDistance=g.weapons.projectiles[0].mesh.position.distanceTo(muzzle);
 for(const [type,x,z] of [['walker',-2,-1],['sprinter',3,-2],['giant',-4,-4]]){const enemy=new Zombie(g.scene,type,new T.Vector3(x,0,z),g.waveManager.models,g.particles,1,g.weapons);enemy.health=Math.ceil(enemy.maxHealth*.65);enemy.healthBar.update(enemy.position,enemy.health,enemy.maxHealth);g.waveManager.enemies.push(enemy);}
 g.player.health=68;g.player.shield=42;g.player.healthBar.update(g.player.position,68,100);g.ui.updateStats(g.player,g.waveManager,1250);g.ui.drawRadar(g.player,g.waveManager.enemies,g.pickups.pickups,g.arena.portals);g.ui.bannerText.classList.remove('show');g.player.updateCamera(1);g.renderer.render(g.scene,g.camera);
 return {cross:cross.toArray(),gunSize:dimensions.toArray(),aimDot:dir.dot(expected),shotDistance,health:document.querySelector('#health-fill').style.width,shield:document.querySelector('#shield-fill').style.width};});
assert.ok(result.cross[2]<-6.9);assert.ok(Math.max(...result.gunSize)>.9);assert.ok(result.aimDot>.999);assert.ok(result.shotDistance<.001);assert.equal(result.health,'68%');assert.equal(result.shield,'42%');await p.screenshot({path:path.join(__dirname,'artifacts','combat-desktop.png')});
await p.setViewportSize({width:390,height:844});await p.screenshot({path:path.join(__dirname,'artifacts','combat-mobile.png')});
for(const selector of ['.combat-vitals','.combat-wave','.combat-loadout']){const box=await p.locator(selector).boundingBox();assert.ok(box.x>=0 && box.x+box.width<=390 && box.y>=0 && box.y+box.height<=844,selector);}
await p.setViewportSize({width:1440,height:900});await p.evaluate(()=>{const g=window.game;g.waveManager.clear();g.player.reset();g.state='PLAYING';g.player.setInputEnabled(true);});await p.keyboard.down('KeyW');await p.waitForFunction(()=>window.game.player.position.z<2);await p.keyboard.up('KeyW');await p.keyboard.press('Digit2');await p.waitForFunction(()=>window.game.weapons.getCurrentWeapon().isKnife && window.game.weapons.weaponMeshes.knife?.visible && document.querySelector('#weapon-name').textContent==='DAO BẾP');
const knife=await p.evaluate(async()=>{const T=await import('/libs/three.module.js');const g=window.game;const k=g.weapons.weaponMeshes.knife;let textured=false;k.traverse(c=>{if(c.isMesh&&c.material.map?.image)textured=true;});g.state='PAUSED';g.player.setInputEnabled(false);g.player.model.rotation.y=Math.PI/2;g.weapons.updateHeldPose(g.player.model);g.camera.left*=.35;g.camera.right*=.35;g.camera.top*=.35;g.camera.bottom*=.35;g.camera.updateProjectionMatrix();g.renderer.render(g.scene,g.camera);return {name:k.name,model:!!k.getObjectByName('cooking-knife'),textured};});
assert.equal(knife.name,'kenney-cooking-knife');assert.equal(knife.model,true);assert.equal(knife.textured,true);await p.screenshot({path:path.join(__dirname,'artifacts','kenney-knife.png')});
await p.evaluate(()=>{window.game.state='PLAYING';window.game.player.setInputEnabled(true);});await p.keyboard.press('Digit1');await p.waitForFunction(()=>window.game.weapons.getCurrentWeapon().id==='blaster');assert.deepEqual(errors,[]);console.log(JSON.stringify({result,errors,checks:'HUD live values, desktop/mobile fit, walk through plaza, gun scale/aim/muzzle, keyboard movement and switching'},null,2));
}finally{if(b)await b.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
